# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  schedule:
    - cron: "0 0 * * 6"

  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

jobs:
  buildnTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  label_issues:
    needs: buildnTest
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - run: gh issue create --title "marche po" --body "test passe pas" --add-label "$LABELS"
    env:
      GH_TOKEN: ${{ github.token }}
      LABELS: Test Failed
